### ISSUE TITLE
Mình ở Viettel. Bên mình đang rất quan tâm tới openhab, bạn có thể cho mình xin contact được không?

### ISSUE THREAD

**Issue by vuasutu** [ngocluanbka/openhab#1]
@ngocluanbka

**Comment by vuasutu** [comment]
@ngocluanbka

**Comment by ngocluanbka** [comment]
@vuasutu Hi bạn. Bạn có thể trao đổi với mình qua email ngocluan.bka@gmail.com nhé. Mình rất vui nếu có thể giúp gì cho bạn.
